name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate protobuf libraries
        run: ./build_proto_libs.sh
      - name: Run unit tests
        run: coverage run -m unittest discover -p "*_test.py"
      - uses: codecov/codecov-action@v1
